<?php

namespace Database\Seeders;

use App\Models\User;
use App\Models\PesertaPpdb;
use Faker\Factory as Faker;
use Illuminate\Support\Carbon;
use Illuminate\Database\Seeder;

class PesertaPpdbSeeder extends Seeder
{
    public function run()
    {
        $faker = Faker::create();

        // Data peserta PPDB
        $dataPeserta = [
            [
                'nama_lengkap' => 'Muhammad Asril',
                'jenis_kelamin' => 'laki-laki',
                'tempat_lahir' => 'Aceh Utara',
                'tanggal_lahir' => '2018-04-16',
                'no_kk' => '1108020812110003',
                'nik_siswa' => '1108021604180003',
                'no_akte_kelahiran' => null,
                'status_pkh' => 'tidak',
                'no_pkh' => '-',
                'sekolah_asal' => '-',
                'agama' => 'islam',
                'alamat' => 'Paloh Lada, Glee Madat, Dewantara, Aceh Utara',
                'tinggal_dengan' => 'Orang Tua',
                'no_telp' => '-',
                'anak_ke' => 'Tiga',
                'jumlah_saudara_kandung' => 'Dua',
                'tinggi_badan' => null,
                'berat_badan' => 15,
            ],
            [
                'nama_lengkap' => 'Husnul Khatimah',
                'jenis_kelamin' => 'perempuan',
                'tempat_lahir' => 'Aceh Utara',
                'tanggal_lahir' => '2018-06-02',
                'no_kk' => '1108022303220001',
                'nik_siswa' => '1108024301190001',
                'no_akte_kelahiran' => '1108-LT-02112020-0088',
                'status_pkh' => 'ada',
                'no_pkh' => '6034 9491 0587 6421',
                'sekolah_asal' => '-',
                'agama' => 'islam',
                'alamat' => 'Glee Madat, Dewantara, Aceh Utara',
                'tinggal_dengan' => 'Orang Tua',
                'no_telp' => '0853-6285-9968',
                'anak_ke' => 'Lima',
                'jumlah_saudara_kandung' => 'Empat',
                'tinggi_badan' => null,
                'berat_badan' => null,
            ],
            [
                'nama_lengkap' => 'Anara Shakila',
                'jenis_kelamin' => 'Perempuan',
                'tempat_lahir' => 'Aceh Utara',
                'tanggal_lahir' => '2018-06-07',
                'no_kk' => '1108020607150002',
                'nik_siswa' => '1108026240800002',
                'no_akte_kelahiran' => '1108-LT-08092021-0076',
                'status_pkh' => 'tidak',
                'no_pkh' => '-',
                'sekolah_asal' => 'Al-Hikmah Mada',
                'agama' => 'islam',
                'alamat' => 'Dusun Madat, Paloh Lada, Dewantara, Aceh Utara',
                'tinggal_dengan' => 'Orang Tua',
                'no_telp' => '0853-5809-7464',
                'anak_ke' => 'Dua',
                'jumlah_saudara_kandung' => 'Dua',
                'tinggi_badan' => null,
                'berat_badan' => null,
            ],
            [
                'nama_lengkap' => 'Zawil Aziza',
                'jenis_kelamin' => 'Perempuan',
                'tempat_lahir' => 'Lhokseumawe',
                'tanggal_lahir' => '2018-07-22',
                'no_kk' => '1108032304180001',
                'nik_siswa' => '1173046207180001',
                'no_akte_kelahiran' => '1108-LT-05082021-0065',
                'status_pkh' => 'tidak',
                'no_pkh' => '-',
                'sekolah_asal' => '-',
                'agama' => 'islam',
                'alamat' => 'Urong Bugeng, Tambon Tunong Dewantara, Aceh Utara',
                'tinggal_dengan' => 'Orang Tua',
                'no_telp' => '0853-6197-7619',
                'anak_ke' => 'Satu',
                'jumlah_saudara_kandung' => 'Satu',
                'tinggi_badan' => 40,
                'berat_badan' => 15,
            ],
            [
                'nama_lengkap' => 'Sofyan Hassouri',
                'jenis_kelamin' => 'Laki-laki',
                'tempat_lahir' => 'Pekan Baru',
                'tanggal_lahir' => '2017-04-10',
                'no_kk' => '1108021502230002',
                'nik_siswa' => '1108024020020001',
                'no_akte_kelahiran' => '1471-LU-10052017-0010',
                'status_pkh' => 'tidak',
                'no_pkh' => '-',
                'sekolah_asal' => 'TKS Madat Ceudah Paloh Lada',
                'agama' => 'islam',
                'alamat' => 'Paloh Gadeng, Dusun-3, Glebaro',
                'tinggal_dengan' => 'Orang Tua',
                'no_telp' => '0812-6981-3944',
                'anak_ke' => 'Satu',
                'jumlah_saudara_kandung' => '-',
                'tinggi_badan' => 117,
                'berat_badan' => 16,
            ],
            [
                'nama_lengkap' => 'Cut Adiva Arsyila Savina',
                'jenis_kelamin' => 'Perempuan',
                'tempat_lahir' => 'Lhokseumawe',
                'tanggal_lahir' => '2018-02-19',
                'no_kk' => '1108022009130003',
                'nik_siswa' => '1108025902180002',
                'no_akte_kelahiran' => '1108-LU-06032018-0007',
                'status_pkh' => 'tidak',
                'no_pkh' => '-',
                'sekolah_asal' => 'TKS Madat Ceudah',
                'agama' => 'islam',
                'alamat' => 'Glee Madat, Paloh Lada, Dewantara, Aceh Utara',
                'tinggal_dengan' => 'Orang Tua',
                'no_telp' => '0853-5845-1472',
                'anak_ke' => 'Dua',
                'jumlah_saudara_kandung' => 'Tiga',
                'tinggi_badan' => null,
                'berat_badan' => null,
            ],
            [
                'nama_lengkap' => 'Sirajuddin',
                'jenis_kelamin' => 'Laki-laki',
                'tempat_lahir' => '',
                'tanggal_lahir' => '2017-11-10',
                'no_kk' => '1108022711060221',
                'nik_siswa' => '1108021011170002',
                'no_akte_kelahiran' => null,
                'status_pkh' => 'tidak',
                'no_pkh' => '-',
                'sekolah_asal' => 'TKS Madat Ceudah',
                'agama' => 'islam',
                'alamat' => 'Dusun-4, Urong Bugeng, Tambon Baro, Dewantara, Aceh Utara',
                'tinggal_dengan' => 'Orang Tua',
                'no_telp' => '0823-6757-9525',
                'anak_ke' => 'Tiga',
                'jumlah_saudara_kandung' => 'Empat',
                'tinggi_badan' => null,
                'berat_badan' => 13,
            ],
            [
                'nama_lengkap' => 'Shally Luthfia',
                'jenis_kelamin' => 'Perempuan',
                'tempat_lahir' => 'Aceh Utara',
                'tanggal_lahir' => '2017-10-31',
                'no_kk' => '1108022606140003',
                'nik_siswa' => '1108027110170002',
                'no_akte_kelahiran' => '1108-LT-08082018-0062',
                'status_pkh' => 'tidak',
                'no_pkh' => '-',
                'sekolah_asal' => 'TKS Madat Ceudah',
                'agama' => 'islam',
                'alamat' => 'Urong Bugeng, Tambon Baro, Dewantara, Aceh Utara',
                'tinggal_dengan' => 'Orang Tua',
                'no_telp' => '0852-2747-5417',
                'anak_ke' => 'Tiga',
                'jumlah_saudara_kandung' => 'Tiga',
                'tinggi_badan' => null,
                'berat_badan' => null,
            ],
            [
                'nama_lengkap' => 'Mahyul Fata',
                'jenis_kelamin' => 'Laki-laki',
                'tempat_lahir' => 'Aceh Utara',
                'tanggal_lahir' => '2018-02-11',
                'no_kk' => '1108023101180006',
                'nik_siswa' => '1108021102180002',
                'no_akte_kelahiran' => '1108-LT-14082018-0084',
                'status_pkh' => 'tidak',
                'no_pkh' => '-',
                'sekolah_asal' => 'TKS Madat Ceudah',
                'agama' => 'islam',
                'alamat' => 'Dusun Madat, Paloh Lada, Dewantara, Aceh Utara',
                'tinggal_dengan' => 'Orang Tua',
                'no_telp' => '0852-6033-2271',
                'anak_ke' => 'Satu',
                'jumlah_saudara_kandung' => '-',
                'tinggi_badan' => null,
                'berat_badan' => null,
            ],
            [
                'nama_lengkap' => 'Cut Khaushatul Aqila',
                'jenis_kelamin' => 'Perempuan',
                'tempat_lahir' => 'Aceh Utara',
                'tanggal_lahir' => '2017-10-07',
                'no_kk' => '1108121306170002',
                'nik_siswa' => '1108124710170002',
                'no_akte_kelahiran' => '1108-LT-23072018-0086',
                'status_pkh' => 'tidak',
                'no_pkh' => '-',
                'sekolah_asal' => 'TKS Madat Ceudah',
                'agama' => 'islam',
                'alamat' => 'Dusun Madat, Paloh Lada, Dewantara, Aceh Utara',
                'tinggal_dengan' => 'Orang Tua',
                'no_telp' => '0822-7349-5932',
                'anak_ke' => 'Satu',
                'jumlah_saudara_kandung' => 'Satu',
                'tinggi_badan' => null,
                'berat_badan' => null,
            ],
            [
                'nama_lengkap' => 'Chalisa Adiva',
                'jenis_kelamin' => 'Perempuan',
                'tempat_lahir' => 'Aceh Utara',
                'tanggal_lahir' => '2018-07-07',
                'no_kk' => '1108020305180002',
                'nik_siswa' => '1108024707180002',
                'no_akte_kelahiran' => '1108-LT-26112018-0050',
                'status_pkh' => 'tidak',
                'no_pkh' => '-',
                'sekolah_asal' => 'TKS Madat Ceudah',
                'agama' => 'islam',
                'alamat' => 'Urong Bugeng, Tambon Tunong Dewantara, Aceh Utara',
                'tinggal_dengan' => 'Orang Tua',
                'no_telp' => '0853-7039-2809',
                'anak_ke' => 'Satu',
                'jumlah_saudara_kandung' => 'Dua',
                'tinggi_badan' => null,
                'berat_badan' => null,
            ],
            [
                'nama_lengkap' => 'Muhammad Afzal',
                'jenis_kelamin' => 'Laki-laki',
                'tempat_lahir' => 'Aceh Utara',
                'tanggal_lahir' => '2017-09-29',
                'no_kk' => '1108020210170004',
                'nik_siswa' => null,
                'no_akte_kelahiran' => '1108-LT-21032018-0001',
                'status_pkh' => 'tidak',
                'no_pkh' => '-',
                'sekolah_asal' => 'TKS Madat Ceudah',
                'agama' => 'islam',
                'alamat' => 'Dusun Madat, Paloh Lada, Dewantara Aceh Utara',
                'tinggal_dengan' => 'Orang Tua',
                'no_telp' => '0823-6385-3707',
                'anak_ke' => 'Satu',
                'jumlah_saudara_kandung' => 'Dua',
                'tinggi_badan' => null,
                'berat_badan' => null,
            ],
            [
                'nama_lengkap' => 'Najwa Faradisa',
                'jenis_kelamin' => 'Perempuan',
                'tempat_lahir' => 'Aceh Utara',
                'tanggal_lahir' => '2018-03-24',
                'no_kk' => '1108020507180001',
                'nik_siswa' => '1108026402180002',
                'no_akte_kelahiran' => '1108-LT-05072018-0040',
                'status_pkh' => 'tidak',
                'no_pkh' => '-',
                'sekolah_asal' => 'TKS Madat Ceudah',
                'agama' => 'islam',
                'alamat' => 'Dusun-5, Urong Bugeng, Tambon Tunong, Dewantara, Aceh Utara',
                'tinggal_dengan' => 'Orang Tua',
                'no_telp' => '0852-8258-1360',
                'anak_ke' => 'Empat',
                'jumlah_saudara_kandung' => 'Lima',
                'tinggi_badan' => null,
                'berat_badan' => null,
            ],
            [
                'nama_lengkap' => 'Rizka Munira',
                'jenis_kelamin' => 'Perempuan',
                'tempat_lahir' => 'Aceh Utara',
                'tanggal_lahir' => '2017-11-02',
                'no_kk' => '1108021511070002',
                'nik_siswa' => '1108024311170003',
                'no_akte_kelahiran' => '1108-LT-26072019-0039',
                'status_pkh' => 'tidak',
                'no_pkh' => '-',
                'sekolah_asal' => 'TKS Madat Ceudah',
                'agama' => 'islam',
                'alamat' => 'BTN PIM Glee Madat, Paloh Lada, Dewantara, Aceh Utara',
                'tinggal_dengan' => 'Orang Tua',
                'no_telp' => '0838-3338-9103',
                'anak_ke' => 'Tujuh',
                'jumlah_saudara_kandung' => 'Delapan',
                'tinggi_badan' => null,
                'berat_badan' => null,
            ],
            [
                'nama_lengkap' => 'Rizki Maulana',
                'jenis_kelamin' => 'Laki-laki',
                'tempat_lahir' => 'Glee Madat',
                'tanggal_lahir' => '2017-12-13',
                'no_kk' => '1108021610170005',
                'nik_siswa' => '1108021312170001',
                'no_akte_kelahiran' => '1108-LU-27122017-0043',
                'status_pkh' => 'tidak',
                'no_pkh' => '-',
                'sekolah_asal' => 'TKS Madat Ceudah',
                'agama' => 'islam',
                'alamat' => 'Glee Madat, Kerani Madsyah, Dewantara, Aceh Utara',
                'tinggal_dengan' => 'Orang Tua',
                'no_telp' => '0823-6052-4633',
                'anak_ke' => 'Dua',
                'jumlah_saudara_kandung' => 'Dua',
                'tinggi_badan' => null,
                'berat_badan' => null,
            ],
            [
                'nama_lengkap' => 'Muhammad Zaki',
                'jenis_kelamin' => 'Laki-laki',
                'tempat_lahir' => 'Lhokseumawe',
                'tanggal_lahir' => '2017-02-28',
                'no_kk' => '1108022010160004',
                'nik_siswa' => '1108022812170001',
                'no_akte_kelahiran' => '1108-LU-02281217-0001',
                'status_pkh' => 'tidak',
                'no_pkh' => '-',
                'sekolah_asal' => 'Tadika Islam Drul Yatama',
                'agama' => 'islam',
                'alamat' => 'Paloh Gadeng, Dusun-1, Dewantara, Aceh Utara',
                'tinggal_dengan' => 'Orang Tua',
                'no_telp' => '0823-6785-6875',
                'anak_ke' => 'Satu',
                'jumlah_saudara_kandung' => 'Dua',
                'tinggi_badan' => 16,
                'berat_badan' => null,
            ],
            [
                'nama_lengkap' => 'Fatih Rizka Fadhila Gulo',
                'jenis_kelamin' => 'Perempuan',
                'tempat_lahir' => 'Aceh Utara',
                'tanggal_lahir' => '2017-12-26',
                'no_kk' => '1108020405180005',
                'nik_siswa' => '1108026612170002',
                'no_akte_kelahiran' => '1108-LT-11122019-0079',
                'status_pkh' => 'tidak',
                'no_pkh' => '-',
                'sekolah_asal' => 'Paud Al-Hikmah Madat',
                'agama' => 'islam',
                'alamat' => 'Paloh Lada, Madat, Dewantara, Aceh Utara',
                'tinggal_dengan' => 'Orang Tua',
                'no_telp' => '0823-6379-5213',
                'anak_ke' => 'Satu',
                'jumlah_saudara_kandung' => 'Dua',
                'tinggi_badan' => 100,
                'berat_badan' => 20,
            ],
            [
                'nama_lengkap' => 'Muhammad Ghautsil',
                'jenis_kelamin' => 'Laki-laki',
                'tempat_lahir' => 'Aceh Utara',
                'tanggal_lahir' => '2018-01-16',
                'no_kk' => '1108022601160006',
                'nik_siswa' => '1108021601180001',
                'no_akte_kelahiran' => '1108-LU-07022018-0005',
                'status_pkh' => 'tidak',
                'no_pkh' => '-',
                'sekolah_asal' => 'Paud Al-Hikmah Madat',
                'agama' => 'islam',
                'alamat' => 'Paloh Lada, Dusun Simpang-3 KKA, Dewantara, Aceh Utara',
                'tinggal_dengan' => 'Orang Tua',
                'no_telp' => '0823-6116-8616',
                'anak_ke' => 'Dua',
                'jumlah_saudara_kandung' => 'Empat',
                'tinggi_badan' => null,
                'berat_badan' => null,
            ],
            [
                'nama_lengkap' => 'Muhammad Azzar Kani',
                'jenis_kelamin' => 'Laki-laki',
                'tempat_lahir' => 'Lhokseumawe',
                'tanggal_lahir' => '2017-09-05',
                'no_kk' => '1108021210110003',
                'nik_siswa' => '110802321170002',
                'no_akte_kelahiran' => '1108-LT-13122017-0342',
                'status_pkh' => 'tidak',
                'no_pkh' => '-',
                'sekolah_asal' => 'Paud Al-Hikmah Madat',
                'agama' => 'islam',
                'alamat' => 'Glee Madat, Paloh Lada, Dewantara, Aceh Utara',
                'tinggal_dengan' => 'Orang Tua',
                'no_telp' => '0813-7621-4403',
                'anak_ke' => 'Dua',
                'jumlah_saudara_kandung' => 'Dua',
                'tinggi_badan' => null,
                'berat_badan' => null,
            ],
            [
                'nama_lengkap' => 'Sayed Yusuf',
                'jenis_kelamin' => 'Laki-laki',
                'tempat_lahir' => 'Lhokseumawe',
                'tanggal_lahir' => '2017-11-04',
                'no_kk' => '1108021105110004',
                'nik_siswa' => '1108020411170003',
                'no_akte_kelahiran' => null,
                'status_pkh' => 'tidak',
                'no_pkh' => '-',
                'sekolah_asal' => 'TKS Madat Ceudah',
                'agama' => 'islam',
                'alamat' => 'Jalan Cemara No.B4 PIM, Dusun Madat, Paloh Lada, Dewantara, Aceh Utara',
                'tinggal_dengan' => 'Orang Tua',
                'no_telp' => '0852-6011-5180',
                'anak_ke' => 'Empat',
                'jumlah_saudara_kandung' => 'Empat',
                'tinggi_badan' => 98,
                'berat_badan' => 18,
            ],
            [
                'nama_lengkap' => 'Muhammad Tsaqif Ar Raqi',
                'jenis_kelamin' => 'Laki-laki',
                'tempat_lahir' => 'Lhokseumawe',
                'tanggal_lahir' => '2018-08-24',
                'no_kk' => '1108082806220002',
                'nik_siswa' => '1173022408180002',
                'no_akte_kelahiran' => '-',
                'status_pkh' => 'tidak',
                'no_pkh' => '-',
                'sekolah_asal' => 'Paud Al-Hikmah Madat',
                'agama' => 'islam',
                'alamat' => 'Dusun Glee Madat, Paloh Lada, Dewantara, Aceh Utara',
                'tinggal_dengan' => 'Orang Tua',
                'no_telp' => '0852-7758-7040',
                'anak_ke' => 'Dua',
                'jumlah_saudara_kandung' => 'Dua',
                'tinggi_badan' => null,
                'berat_badan' => null,
            ],
            [
                'nama_lengkap' => 'Najmuddin',
                'jenis_kelamin' => 'Laki-laki',
                'tempat_lahir' => 'Paloh Gadeng',
                'tanggal_lahir' => '2017-04-03',
                'no_kk' => '1108021011060435',
                'nik_siswa' => '1108020304170003',
                'no_akte_kelahiran' => '1108-LT-12092017-0115',
                'status_pkh' => 'tidak',
                'no_pkh' => '-',
                'sekolah_asal' => 'Paud Al-Hikmah Madat',
                'agama' => 'islam',
                'alamat' => 'Paloh Gadeng, Dusun-3, Glee Baro, Dewantara, Aceh Utara',
                'tinggal_dengan' => 'Orang Tua',
                'no_telp' => '0813-6000-6239',
                'anak_ke' => 'Enam',
                'jumlah_saudara_kandung' => 'Enam',
                'tinggi_badan' => null,
                'berat_badan' => null,
            ],
            [
                'nama_lengkap' => 'Hauratul Jinan',
                'jenis_kelamin' => 'Perempuan',
                'tempat_lahir' => 'Aceh Utara',
                'tanggal_lahir' => '2018-06-26',
                'no_kk' => '1108020507180005',
                'nik_siswa' => '1108026606180004',
                'no_akte_kelahiran' => '1108-LT-20092021-0079',
                'status_pkh' => 'tidak',
                'no_pkh' => '-',
                'sekolah_asal' => 'Paud AL-Hikam',
                'agama' => 'islam',
                'alamat' => 'Glee Madat, Paloh Lada, Dewantara, Aceh Utara',
                'tinggal_dengan' => 'Orang Tua',
                'no_telp' => '0853-6285-7682',
                'anak_ke' => 'Satu',
                'jumlah_saudara_kandung' => 'Satu',
                'tinggi_badan' => null,
                'berat_badan' => 16,
            ],
            [
                'nama_lengkap' => 'Nasla Annafisa',
                'jenis_kelamin' => 'Perempuan',
                'tempat_lahir' => 'Lhokseumawe',
                'tanggal_lahir' => '2018-03-12',
                'no_kk' => '1108021102150005',
                'nik_siswa' => '1108025203180001',
                'no_akte_kelahiran' => null,
                'status_pkh' => 'tidak',
                'no_pkh' => '-',
                'sekolah_asal' => null,
                'agama' => 'islam',
                'alamat' => 'Dusun Madat, Paloh Lada, Dewantara, Aceh',
                'tinggal_dengan' => 'Orang Tua',
                'no_telp' => '-',
                'anak_ke' => 'Satu',
                'jumlah_saudara_kandung' => 'Satu',
                'tinggi_badan' => null,
                'berat_badan' => null,
            ],
            [
                'nama_lengkap' => 'Siti Maysarah',
                'jenis_kelamin' => 'Perempuan',
                'tempat_lahir' => 'Lhokseumawe',
                'tanggal_lahir' => '2018-06-11',
                'no_kk' => '1108071904180001',
                'nik_siswa' => '1108075106180001',
                'no_akte_kelahiran' => '1108-LT-10012023-0015',
                'status_pkh' => 'tidak',
                'no_pkh' => '-',
                'sekolah_asal' => 'Paud Al-Hikmah Madat',
                'agama' => 'islam',
                'alamat' => 'Glee Madat, Paloh Lada, Dewantara, Aceh Utara',
                'tinggal_dengan' => 'Orang Tua',
                'no_telp' => '0822-7464-9349',
                'anak_ke' => 'Satu',
                'jumlah_saudara_kandung' => 'Dua',
                'tinggi_badan' => null,
                'berat_badan' => null,
            ],
            [
                'nama_lengkap' => 'T. Muhammad Fuzari',
                'jenis_kelamin' => 'Laki-laki',
                'tempat_lahir' => 'Aceh Utara',
                'tanggal_lahir' => '2018-05-12',
                'no_kk' => '1108022505110002',
                'nik_siswa' => '1108021911170002',
                'no_akte_kelahiran' => '1108-LT-24012019-0086',
                'status_pkh' => 'tidak',
                'no_pkh' => '-',
                'sekolah_asal' => 'Paud Al-Hikmah Madat',
                'agama' => 'islam',
                'alamat' => 'Glee Madat, Paloh Lada, Dewantara, Aceh Utara',
                'tinggal_dengan' => 'Orang Tua',
                'no_telp' => '0853-6257-7313',
                'anak_ke' => 'Empat',
                'jumlah_saudara_kandung' => 'Empat',
                'tinggi_badan' => null,
                'berat_badan' => null,
            ],
            [
                'nama_lengkap' => 'Abrar Azizi',
                'jenis_kelamin' => 'Laki-laki',
                'tempat_lahir' => 'Aceh Utara',
                'tanggal_lahir' => '2018-05-25',
                'no_kk' => '1108021411060212',
                'nik_siswa' => '1108022505180004',
                'no_akte_kelahiran' => '1108-LT-28022019-0029',
                'status_pkh' => 'ada',
                'no_pkh' => '6034 9491 0587 2050',
                'sekolah_asal' => 'Paud Al-Hikmah Madat',
                'agama' => 'islam',
                'alamat' => 'Glee Madat, Paloh Lada, Dewantara, Aceh Utara',
                'tinggal_dengan' => 'Orang Tua',
                'no_telp' => '-',
                'anak_ke' => 'Lima',
                'jumlah_saudara_kandung' => 'Lima',
                'tinggi_badan' => null,
                'berat_badan' => null,
            ],
            [
                'nama_lengkap' => 'Nurfahiya',
                'jenis_kelamin' => 'Perempuan',
                'tempat_lahir' => 'TB Tunong',
                'tanggal_lahir' => '2017-09-06',
                'no_kk' => '1108020402080003',
                'nik_siswa' => '1108024609170001',
                'no_akte_kelahiran' => '1108-LT-12012018-0298',
                'status_pkh' => 'tidak',
                'no_pkh' => '-',
                'sekolah_asal' => null,
                'agama' => 'islam',
                'alamat' => 'Dusun-4, Urong Bugeng, Tambon Tunong, Dewantara, Aceh Utara',
                'tinggal_dengan' => 'Orang Tua',
                'no_telp' => '0852-1080-8583',
                'anak_ke' => 'Tiga',
                'jumlah_saudara_kandung' => 'Tiga',
                'tinggi_badan' => null,
                'berat_badan' => 15,
            ],
        ];

        foreach ($dataPeserta as $peserta) {
            // Cari user_id berdasarkan nama dari tabel users
            $user = User::where('name', $peserta['nama_lengkap'])->first();
            // Jika user tidak ditemukan, buat user_id dengan random UUID
            $user_id = $user ? $user->id : $faker->uuid;

            // Isi nilai null atau acak untuk kolom yang kosong
            PesertaPpdb::create([
                'user_id' => $user_id,
                'name' => $peserta['nama_lengkap'],
                'jenis_kelamin' => $peserta['jenis_kelamin'],
                'tempat_lahir' => $peserta['tempat_lahir'] ?? $faker->city,
                'tanggal_lahir' => $peserta['tanggal_lahir'],
                'kk' => $peserta['no_kk'] ?? $faker->numerify('###############'),
                'nik' => $peserta['nik_siswa'] ?? $faker->numerify('###############'),
                'no_akte_kelahiran' => $peserta['no_akte_kelahiran'] ?? '-',
                'status_pkh' => $peserta['status_pkh'],
                'no_pkh' => $peserta['no_pkh'] === '-' ? '-' : ($peserta['no_pkh'] ?? $faker->numerify('################')),
                'asal_sekolah' => $peserta['sekolah_asal'] === '-' ? '-' : ($peserta['sekolah_asal'] ?? $faker->company),
                'agama' => $peserta['agama'] ?? 'islam',
                'alamat' => $peserta['alamat'] ?? $faker->address,
                'tinggal_dengan' => $peserta['tinggal_dengan'] ?? 'Orang Tua',
                'no_telp' => $peserta['no_telp'] === '-' ? '-' : ($peserta['no_telp'] ?? $faker->phoneNumber),
                'anak_ke' => $peserta['anak_ke'] ?? $faker->randomDigitNotNull,
                'jml_saudara_kandung' => $peserta['jumlah_saudara_kandung'] ?? $faker->randomDigitNotNull,
                'tinggi_badan' => $peserta['tinggi_badan'] ?? $faker->randomFloat(2, 50, 150),
                'berat_badan' => $peserta['berat_badan'] ?? $faker->randomFloat(2, 10, 50),
                'status' => 'verifikasi',
                'created_at' => Carbon::create(2024, 5, rand(1, 31)), // Tahun 2024 dengan hari acak
                'updated_at' => Carbon::create(2024, 5, rand(1, 31)), // Tahun 2024 dengan hari acak

            ]);
        }
    }
}
